export const MISSIONS = [
  {
    key: "first_purchase",
    title: "Primera compra",
    description: "Completa tu primera orden en CIBOX",
    reward: "5% de descuento",
    discount_type: "percent",
    discount_value: 5,
    icon: "🛒",
    color: "#4E9B27",
    order: 1,
  },
  {
    key: "complete_profile",
    title: "Completa tu perfil",
    description: "Agrega tu nombre, teléfono y RUT a tu cuenta",
    reward: "3% de descuento",
    discount_type: "percent",
    discount_value: 3,
    icon: "👤",
    color: "#2196F3",
    order: 2,
  },
  {
    key: "five_favorites",
    title: "Colecciona favoritos",
    description: "Agrega 5 productos a tus favoritos",
    reward: "$300 de descuento",
    discount_type: "fixed",
    discount_value: 300,
    icon: "❤️",
    color: "#E91E63",
    order: 3,
  },
  {
    key: "leave_review",
    title: "Deja una reseña",
    description: "Comparte tu opinión sobre un producto comprado",
    reward: "$200 de descuento",
    discount_type: "fixed",
    discount_value: 200,
    icon: "⭐",
    color: "#FF9800",
    order: 4,
  },
  {
    key: "share_app",
    title: "Comparte CIBOX",
    description: "Recomienda la app a un amigo usando el botón compartir",
    reward: "$500 de descuento",
    discount_type: "fixed",
    discount_value: 500,
    icon: "📢",
    color: "#9C27B0",
    order: 5,
  },
];